Enforce check on relocatable bottle before install
Check on relocatability of bottle is [performed at bottle
creation](https://github.com/Homebrew/brew/blob/ad4fd014e1e558207d4eecdafe8667ecba5a8f51/Library/Homebrew/dev-cmd/bottle.rb#L231)
and logged by the [bot](https://bot.brew.sh/job/Homebrew%20Core/)
(stored only for some time though).

Check on pourability of bottle (not based only on relocatability) is
[performed at installation
time](https://github.com/Homebrew/brew/blob/c5072226871196d2eb3265d930daff87968d23e8/Library/Homebrew/formula_installer.rb#L80-L114). Invoke
such code by using
[IRB](https://github.com/Homebrew/brew/blob/c5072226871196d2eb3265d930daff87968d23e8/Library/Homebrew/cmd/irb.rb#L33)
(and paying attention to [IRB exit
status](https://www.pgrs.net/2007/10/10/do-not-trust-irb-exit-status/).

Clean solution would be new option for `brew install`.

Also:
* Remove `set -e` as it complicates conditionals;
* Reduce scope of Firefox-related variables;
* Clean some conditionals.

diff --git a/libexec/brew_install b/libexec/brew_install
--- a/libexec/brew_install
+++ b/libexec/brew_install
@@ -2,17 +2,33 @@
 
 ## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>
 
-RB="" ## Annotation for expected relocatable bottle.
-
-set -e
+## Has the specified brew formula got a pourable bottle?
+##
+## Exits with code:
+## * 0 if formula exists and has a pourable bottle;
+## * 1 if formula does not exist or has not a pourable bottle.
+has_pb() {
+    printf \
+        "require 'formula_installer'; fn = '%s'; f = fn.f rescue abort('maybe formula ' + fn + ' does not exist?'); if FormulaInstaller.new(f).pour_bottle? then exit() else abort('bottle of formula ' + f.full_name + ' not pourable') end" \
+        "${1:?}" \
+        | { brew irb > /dev/null; }
+}
 
 ROOT_DIR="$(cd $(dirname $0)/.. && pwd)"
 
-brew cask install Caskroom/cask/iterm2 ## No Sixel support (VT340) - [ref](https://gitlab.com/gnachman/iterm2/issues/3240).
-brew install ${RB?} tmux
-brew install bash-completion
-brew install git ## For git-completion.
-brew install emacs --with-modules && { test -e "${HOME}/.emacs" && { test -e "${HOME}/.emacs.d" && $(brew --prefix emacs)/bin/emacs --batch --eval "(require 'package)" -f package-initialize --eval "(require 'epl)" -f epl-refresh -f epl-upgrade; }; }
+brew cask install Caskroom/cask/iterm2 || exit 1 ## No Sixel support (VT340) - [ref](https://gitlab.com/gnachman/iterm2/issues/3240).
+{ has_pb tmux && brew install tmux; } || exit 1
+brew install bash-completion || exit 1
+brew install git || exit 1 ## For git-completion.
+{ brew install emacs --with-modules && \
+      if test -e "${HOME}/.emacs"; then
+          if test -e "${HOME}/.emacs.d"; then
+              "$(brew --prefix emacs)/bin/emacs" \
+                  --batch \
+                  --eval "(require 'package)" -f package-initialize \
+                  --eval "(require 'epl)" -f epl-refresh -f epl-upgrade
+          fi
+      fi; } || exit 1
 
 ## Refs:
 ## * curl `-z`, curl `-w`: http://blog.yjl.im/2012/03/downloading-only-when-modified-using.html
@@ -25,59 +41,61 @@ brew install emacs --with-modules && { test -e "${HOME}/.emacs" && { test -e "${
 ##
 ## If curl `-z <date expression>` option needed, related standard for
 ## expressing time is RFC 5322.
-FfD="${HOME}/homebrew-cask/Caskroom/firefoxdeveloperedition/latest" ## HACK
-FfUrl="https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=osx&lang=en-US" ## HACK Ref https://github.com/caskroom/homebrew-versions/commit/a3c21d439ba0fd09419ef720b843708980f6171f#diff-482097f2c80e9571c53aab608b5eb705L5
-test -d "$FfD" || echo "Firefox-related directory '$FfD' not found: first time installation? Continuing."
-FfC=$(curl -s -S -L --head -o /dev/null -w '%{http_code}' -z "$FfD" "$FfUrl")
-case "${FfC:?}" in
-    304) echo "No more recent Firefox Developer Edition to install. Skipping." >&2;;
-    200) brew cask install --force caskroom/versions/firefoxdeveloperedition;;
-    *) echo "Check for Firefox Developer Edition returned unknown HTTP status code '${FfC}'. Exiting." >&2; exit 1
+(
+    FfD="${HOME}/homebrew-cask/Caskroom/firefoxdeveloperedition/latest" ## HACK
+    FfUrl="https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=osx&lang=en-US" ## HACK Ref https://github.com/caskroom/homebrew-versions/commit/a3c21d439ba0fd09419ef720b843708980f6171f#diff-482097f2c80e9571c53aab608b5eb705L5
+    test -d "$FfD" || echo "Firefox-related directory '$FfD' not found: first time installation? Continuing." >&2
+    FfC=$(curl -s -S -L --head -o /dev/null -w '%{http_code}' -z "$FfD" "$FfUrl") || { echo "Check for Firefox Developer Edition failed. Exiting." >&2; exit 1; }
+    case "${FfC:?}" in
+        304) echo "No more recent Firefox Developer Edition to install. Skipping." >&2;;
+        200) brew cask install --force caskroom/versions/firefoxdeveloperedition;;
+        *) echo "Check for Firefox Developer Edition returned unknown HTTP status code '${FfC}'. Exiting." >&2; exit 1
 esac
+) || exit 1
 
-#brew install packer
-brew install docker
-brew install docker-machine ## Downloads boot2docker.iso
-#brew install docker-machine-driver-xhyve ## docker-machine does not adhere to the specified driver. See https://github.com/zchee/docker-machine-driver-xhyve/issues/128
-brew install ${RB?} ansible
-#brew install ssh-copy-id
+#brew install packer || exit 1
+brew install docker || exit 1
+brew install docker-machine || exit 1 ## Downloads boot2docker.iso
+#brew install docker-machine-driver-xhyve || exit 1 ## docker-machine does not adhere to the specified driver. See https://github.com/zchee/docker-machine-driver-xhyve/issues/128
+{ has_pb ansible && brew install ansible; } || exit 1
+#brew install ssh-copy-id || exit 1
 
-#brew install android-platform-tools ## adb
-#brew install android-sdk ## For IntelliJ.
-#brew cask install android-studio ## From [IntelliJ IDEA and Android Studio FAQ](http://blog.jetbrains.com/idea/2013/05/intellij-idea-and-android-studio-faq/): "If I’m already a user of IntelliJ IDEA, do I need to switch to Android Studio for Android development? No. Android Studio is focused specifically on Android development and provides streamlined environment and project setup, but otherwise all of its features are available in IntelliJ IDEA."
-brew install autoconf
-#brew install bats
-brew install checkbashisms
-#brew install cmake
-#brew install cvs
-#brew install cvs2svn
-#brew install dash
-#brew install gcc
-#brew install gdb
-{ brew rm ctags || true; } && { { brew rm universal-ctags/universal-ctags/universal-ctags || true; } && brew install --HEAD universal-ctags/universal-ctags/universal-ctags; } && { brew install lucafavatella/core/global --with-universal-ctags --with-pygments || exit 1; } && { cat $(brew --prefix global)/share/gtags/gtags.conf | sed 's/^	:tc=native:$/	:tc=pygments:/' > $(brew --prefix)/etc/gtags.conf || exit 1; } ## After many universal-ctags parsers support references, pygments can be dropped (and maybe GNU GLOBAL - relying on universal-ctags output for both definitions and references). Refs https://github.com/universal-ctags/ctags/pull/569#issuecomment-156300213 http://cvs.savannah.gnu.org/viewvc/global/global/configure.ac?r1=1.178&r2=1.179
-#brew install ${RB?} ghc && brew install cabal-install && PATH="$(brew --prefix)/bin:$PATH" cabal update && PATH="$(brew --prefix)/bin:$PATH" cabal install idris
-#brew cask install caskroom/versions/intellij-idea-ce
-#brew install ${RB?} jq
-brew install kerl
-#brew install saitoha/sixel/mlterm ## Refs https://en.wikipedia.org/wiki/VT340 https://en.wikipedia.org/wiki/Sixel
-#brew install node ## Installs `npm` too.
-brew install openssl ## Install openssl - for building Erlang/OTP without skipping the crypto application [on MacOSX >= 10.11](http://erlang.org/pipermail/erlang-questions/2015-October/086386.html).
-brew install p7zip ## `7z x` works as a compression-agnostic archive extractor command better than BSD `tar -x` e.g. for `gzip` compression.
-#brew install plantuml
-#brew install pstree
-#brew install pup
-brew install python && "$(brew --prefix python)/bin/pip" install --upgrade pip setuptools ## Ref https://github.com/Homebrew/homebrew/blob/0333865e5d831faa6fd6a414fe19e486898aceba/Library/Formula/python.rb#L321-L322
-brew install python3 && "$(brew --prefix python3)/bin/pip3" install --upgrade pip setuptools ## Ref https://github.com/Homebrew/homebrew/blob/cfcbf92dedb275bdf06597745d9dcd392dcb2fbb/Library/Formula/python3.rb#L314-L315
-#"$(brew --prefix python)/bin/pip" install numpy && brew install OSGeo/osgeo4mac/qgis2 --without-postgresql || exit 1
-#brew install rust
-#brew install shellcheck
-#brew install ${RB?} sqlite
-#brew install valgrind
-#brew install watch
-brew install ${RB?} wxmac ## Install wxWidgets - for building Erlang/OTP.
+#brew install android-platform-tools || exit 1 ## adb
+#brew install android-sdk || exit 1 ## For IntelliJ.
+#brew cask install android-studio || exit 1 ## From [IntelliJ IDEA and Android Studio FAQ](http://blog.jetbrains.com/idea/2013/05/intellij-idea-and-android-studio-faq/): "If I’m already a user of IntelliJ IDEA, do I need to switch to Android Studio for Android development? No. Android Studio is focused specifically on Android development and provides streamlined environment and project setup, but otherwise all of its features are available in IntelliJ IDEA."
+brew install autoconf || exit 1
+#brew install bats || exit 1
+brew install checkbashisms || exit 1
+#brew install cmake || exit 1
+#brew install cvs || exit 1
+#brew install cvs2svn || exit 1
+#brew install dash || exit 1
+#brew install gcc || exit 1
+#brew install gdb || exit 1
+{ { brew rm ctags || true; } && { { brew rm universal-ctags/universal-ctags/universal-ctags || true; } && brew install --HEAD universal-ctags/universal-ctags/universal-ctags; } && brew install lucafavatella/core/global --with-universal-ctags --with-pygments && { cat $(brew --prefix global)/share/gtags/gtags.conf | sed 's/^	:tc=native:$/	:tc=pygments:/' > $(brew --prefix)/etc/gtags.conf; }; } || exit 1 ## After many universal-ctags parsers support references, pygments can be dropped (and maybe GNU GLOBAL - relying on universal-ctags output for both definitions and references). Refs https://github.com/universal-ctags/ctags/pull/569#issuecomment-156300213 http://cvs.savannah.gnu.org/viewvc/global/global/configure.ac?r1=1.178&r2=1.179
+{ has_pb ghc; } || exit 1 # && brew install ghc && brew install cabal-install && PATH="$(brew --prefix)/bin:$PATH" cabal update && PATH="$(brew --prefix)/bin:$PATH" cabal install idris; } || exit 1
+#brew cask install caskroom/versions/intellij-idea-ce || exit 1
+{ has_pb jq; } || exit 1 # && brew install jq; } || exit 1
+brew install kerl || exit 1
+#brew install saitoha/sixel/mlterm || exit 1 ## Refs https://en.wikipedia.org/wiki/VT340 https://en.wikipedia.org/wiki/Sixel
+#brew install node || exit 1 ## Installs `npm` too.
+brew install openssl || exit 1 ## Install openssl - for building Erlang/OTP without skipping the crypto application [on MacOSX >= 10.11](http://erlang.org/pipermail/erlang-questions/2015-October/086386.html).
+brew install p7zip || exit 1 ## `7z x` works as a compression-agnostic archive extractor command better than BSD `tar -x` e.g. for `gzip` compression.
+#brew install plantuml || exit 1
+#brew install pstree || exit 1
+#brew install pup || exit 1
+{ brew install python && "$(brew --prefix python)/bin/pip" install --upgrade pip setuptools; } || exit 1 ## Ref https://github.com/Homebrew/homebrew/blob/0333865e5d831faa6fd6a414fe19e486898aceba/Library/Formula/python.rb#L321-L322
+{ brew install python3 && "$(brew --prefix python3)/bin/pip3" install --upgrade pip setuptools; } || exit 1 ## Ref https://github.com/Homebrew/homebrew/blob/cfcbf92dedb275bdf06597745d9dcd392dcb2fbb/Library/Formula/python3.rb#L314-L315
+#{ "$(brew --prefix python)/bin/pip" install numpy && brew install OSGeo/osgeo4mac/qgis2 --without-postgresql; } || exit 1
+#brew install rust || exit 1
+#brew install shellcheck || exit 1
+{ has_pb sqlite; } || exit 1 # && brew install sqlite; } || exit 1
+#brew install valgrind || exit 1
+#brew install watch || exit 1
+{ has_pb wxmac && brew install wxmac; } || exit 1 ## Install wxWidgets - for building Erlang/OTP.
 
-#brew install --with-deps dinkypumpkin/get_iplayer/get_iplayer
+#brew install --with-deps dinkypumpkin/get_iplayer/get_iplayer || exit 1
 
-#brew cask install hipchat
-#brew cask install libreoffice
-#brew cask install vlc
+#brew cask install hipchat || exit 1
+#brew cask install libreoffice || exit 1
+#brew cask install vlc || exit 1
